### REgister
POST localhost:8080/api/v1/auth/default


###
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "fullName": "b",
  "role": "ADMIN",
  "email": "b@gmail.com",
  "password": "b"
}

###
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "b@gmail.com",
  "password": "b"
}

###
GET https://52aa-193-104-179-125.ngrok-free.app/api/v1/auth/get-all?page=2&size=5
ngrok-skip-browser-warning: false

###
GET localhost:8080/api/v1/auth/get-all-by/false?page=0&size=5
###
GET  https://a7a0-195-158-9-110.ngrok-free.app/hello